modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/OrderedChaos-Dev/CozyConiferous/issues"
license="lol"

[[mods]]
	modId="cozyconiferous"
	version="${version}"
	displayName="Cozy Coniferous"
	displayURL="https://www.ordered-chaos.dev/"
	logoFile="cc.png"
	authors="solis_nova"
	description='A collection of biomes with a coniferous theme!'
[[dependencies.cozyconiferous]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cozyconiferous]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,]"
    ordering="NONE"
    side="BOTH"
